name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Install node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ github.TOKEN }}          
          release: true
